export interface Product {
  id: string
  name: string
  description: string
  shortDescription: string
  price: number
  originalPrice?: number
  category: string
  brand: string
  image: string
  images?: string[]
  features: string[]
  specifications: Record<string, string>
  inStock: boolean
  rating: number
  reviewCount: number
  badge?: string
}

export const categories = [
  { id: "smartphones", name: "Smartphones", icon: "smartphone", count: 45 },
  { id: "laptops", name: "Laptops", icon: "laptop", count: 32 },
  { id: "smart-watches", name: "Smart Watches", icon: "watch", count: 28 },
  { id: "earbuds", name: "Earbuds", icon: "headphones", count: 35 },
  { id: "speakers", name: "Speakers", icon: "speaker", count: 18 },
  { id: "accessories", name: "Accessories", icon: "accessibility", count: 52 },
  { id: "chargers", name: "Chargers", icon: "battery-charging", count: 22 },
  { id: "power-banks", name: "Power Banks", icon: "battery", count: 15 },
  { id: "cables", name: "Cables", icon: "cable", count: 30 },
]

export const brands = [
  { id: "samsung", name: "Samsung", logo: "/brands/samsung.svg", productCount: 85 },
  { id: "xiaomi", name: "Xiaomi", logo: "/brands/xiaomi.svg", productCount: 62 },
  { id: "vivo", name: "Vivo", logo: "/brands/vivo.svg", productCount: 45 },
  { id: "oppo", name: "Oppo", logo: "/brands/oppo.svg", productCount: 38 },
  { id: "realme", name: "Realme", logo: "/brands/realme.svg", productCount: 42 },
  { id: "apple", name: "Apple", logo: "/brands/apple.svg", productCount: 56 },
  { id: "oneplus", name: "OnePlus", logo: "/brands/oneplus.svg", productCount: 34 },
  { id: "lenovo", name: "Lenovo", logo: "/brands/lenovo.svg", productCount: 48 },
  { id: "hp", name: "HP", logo: "/brands/hp.svg", productCount: 41 },
  { id: "dell", name: "Dell", logo: "/brands/dell.svg", productCount: 37 },
  { id: "asus", name: "ASUS", logo: "/brands/asus.svg", productCount: 33 },
]

export const products: Product[] = [
  {
    id: "galaxy-s24-ultra",
    name: "Samsung Galaxy S24 Ultra",
    description: "Experience the ultimate smartphone with Galaxy AI, 200MP camera, and S Pen built-in. The most powerful Galaxy ever.",
    shortDescription: "200MP Camera • Galaxy AI • S Pen • 6.8\" Dynamic AMOLED 2X",
    price: 129999,
    originalPrice: 139999,
    category: "smartphones",
    brand: "samsung",
    image: "/products/galaxy-s24-ultra.svg",
    images: [
      "/products/galaxy-s24-ultra-1.svg",
      "/products/galaxy-s24-ultra-2.svg",
      "/products/galaxy-s24-ultra-3.svg",
    ],
    features: [
      "200MP Main Camera with 100x Space Zoom",
      "Galaxy AI for intelligent features",
      "Built-in S Pen for productivity",
      "6.8\" Dynamic AMOLED 2X 120Hz Display",
      "Snapdragon 8 Gen 3 for Galaxy",
      "5000mAh Battery with 45W Fast Charging",
    ],
    specifications: {
      Display: "6.8\" QHD+ Dynamic AMOLED 2X, 120Hz",
      Processor: "Snapdragon 8 Gen 3 for Galaxy",
      RAM: "12GB",
      Storage: "256GB / 512GB / 1TB",
      RearCamera: "200MP + 50MP + 12MP + 10MP",
      FrontCamera: "12MP",
      Battery: "5000mAh",
      OS: "One UI 6.1 (Android 14)",
    },
    inStock: true,
    rating: 4.8,
    reviewCount: 1247,
    badge: "Best Seller",
  },
  {
    id: "iphone-15-pro-max",
    name: "iPhone 15 Pro Max",
    description: "Titanium design. A17 Pro chip. Pro camera system. The most Pro iPhone ever.",
    shortDescription: "A17 Pro • 48MP Main • Titanium • 6.7\" Super Retina XDR",
    price: 159900,
    originalPrice: 164900,
    category: "smartphones",
    brand: "apple",
    image: "/products/iphone-15-pro-max.svg",
    images: [
      "/products/iphone-15-pro-max-1.svg",
      "/products/iphone-15-pro-max-2.svg",
    ],
    features: [
      "A17 Pro Chip with 6-Core GPU",
      "48MP Main Camera with ProRAW",
      "5x Optical Zoom Tetraprism Lens",
      "Titanium Design with Action Button",
      "USB-C with USB 3 Speeds",
      "All-Day Battery Life",
    ],
    specifications: {
      Display: "6.7\" Super Retina XDR, 120Hz ProMotion",
      Processor: "A17 Pro",
      RAM: "8GB",
      Storage: "256GB / 512GB / 1TB",
      RearCamera: "48MP + 12MP + 12MP",
      FrontCamera: "12MP TrueDepth",
      Battery: "Up to 29 hours video playback",
      OS: "iOS 17",
    },
    inStock: true,
    rating: 4.9,
    reviewCount: 2156,
    badge: "Flagship",
  },
  {
    id: "macbook-air-m3",
    name: "MacBook Air M3",
    description: "Supercharged by M3 chip. Up to 18 hours battery life. Incredibly thin and light.",
    shortDescription: "M3 Chip • 13.6\" Liquid Retina • 18hr Battery • 1.24kg",
    price: 114900,
    originalPrice: 119900,
    category: "laptops",
    brand: "apple",
    image: "/products/macbook-air-m3.svg",
    images: [
      "/products/macbook-air-m3-1.svg",
      "/products/macbook-air-m3-2.svg",
    ],
    features: [
      "Apple M3 Chip with 8-Core CPU",
      "10-Core GPU for Graphics",
      "13.6\" Liquid Retina Display",
      "Up to 18 Hours Battery Life",
      "Fanless Silent Design",
      "Two Thunderbolt / USB 4 Ports",
    ],
    specifications: {
      Display: "13.6\" Liquid Retina, 2560x1664",
      Processor: "Apple M3 (8-core CPU, 10-core GPU)",
      RAM: "8GB / 16GB / 24GB Unified Memory",
      Storage: "256GB / 512GB / 1TB / 2TB SSD",
      Ports: "2x Thunderbolt/USB 4, MagSafe 3, 3.5mm",
      Camera: "1080p FaceTime HD",
      Battery: "52.6Wh, Up to 18 hours",
      Weight: "1.24 kg",
    },
    inStock: true,
    rating: 4.7,
    reviewCount: 892,
    badge: "Popular",
  },
  {
    id: "dell-xps-14",
    name: "Dell XPS 14 (9440)",
    description: "Premium ultraportable with Intel Core Ultra, optional OLED, and stunning design.",
    shortDescription: "Intel Core Ultra 7 • 14.5\" 3.2K OLED • RTX 4050 • 1.68kg",
    price: 189990,
    originalPrice: 199990,
    category: "laptops",
    brand: "dell",
    image: "/products/dell-xps-14.svg",
    images: [
      "/products/dell-xps-14-1.svg",
      "/products/dell-xps-14-2.svg",
    ],
    features: [
      "Intel Core Ultra 7 Processor",
      "NVIDIA GeForce RTX 4050 (Optional)",
      "14.5\" 3.2K OLED Touch Display",
      "Premium CNC Aluminum Chassis",
      "Quad Speakers with Waves Nx",
      "Thunderbolt 4 & USB-C",
    ],
    specifications: {
      Display: "14.5\" 3.2K (3200x2000) OLED Touch, 120Hz",
      Processor: "Intel Core Ultra 7 155H",
      RAM: "16GB / 32GB / 64GB LPDDR5x",
      Storage: "512GB / 1TB / 2TB / 4TB SSD",
      Graphics: "Intel Arc / NVIDIA RTX 4050",
      Ports: "2x Thunderbolt 4, 1x USB-C 3.2, microSD",
      Battery: "72Wh, ExpressCharge 1.0",
      Weight: "1.68 kg",
    },
    inStock: true,
    rating: 4.6,
    reviewCount: 423,
    badge: "Premium",
  },
  {
    id: "galaxy-watch6-classic",
    name: "Galaxy Watch6 Classic",
    description: "Iconic rotating bezel. Advanced health monitoring. Wear OS 4.",
    shortDescription: "Rotating Bezel • BioActive Sensor • Wear OS 4 • 40mm/47mm",
    price: 36999,
    originalPrice: 39999,
    category: "smart-watches",
    brand: "samsung",
    image: "/products/galaxy-watch6-classic.svg",
    images: [
      "/products/galaxy-watch6-classic-1.svg",
      "/products/galaxy-watch6-classic-2.svg",
    ],
    features: [
      "Signature Rotating Bezel",
      "Samsung BioActive Sensor",
      "Advanced Sleep Coaching",
      "Body Composition Analysis",
      "Wear OS 4 with One UI 5 Watch",
      "Sapphire Crystal Display",
    ],
    specifications: {
      Display: "1.3\" / 1.5\" Super AMOLED, Sapphire Crystal",
      Processor: "Exynos W930 Dual-Core",
      RAM: "2GB",
      Storage: "16GB",
      Sensors: "BioActive (HR, ECG, BIA), Accelerometer, Barometer, Gyro",
      Battery: "300mAh / 425mAh",
      Connectivity: "Bluetooth 5.3, Wi-Fi, LTE (Optional)",
      WaterResistance: "5ATM + IP68 / MIL-STD-810H",
    },
    inStock: true,
    rating: 4.5,
    reviewCount: 678,
  },
  {
    id: "airpods-pro-2",
    name: "AirPods Pro (2nd Gen)",
    description: "Next-level Active Noise Cancellation. Adaptive Transparency. Personalized Spatial Audio.",
    shortDescription: "ANC 2x Better • H2 Chip • Spatial Audio • USB-C Case",
    price: 24900,
    originalPrice: 26900,
    category: "earbuds",
    brand: "apple",
    image: "/products/airpods-pro-2.svg",
    images: [
      "/products/airpods-pro-2-1.svg",
      "/products/airpods-pro-2-2.svg",
    ],
    features: [
      "Up to 2x More Active Noise Cancellation",
      "Adaptive Transparency Mode",
      "Personalized Spatial Audio",
      "H2 Chip for Audio Processing",
      "USB-C Charging Case with Precision Finding",
      "Up to 6 Hours Listening (ANC On)",
    ],
    specifications: {
      Driver: "Custom High-Excursion Apple Driver",
      Chip: "H2 + U1 (Case)",
      NoiseCancellation: "Active Noise Cancellation, Adaptive Transparency",
      Audio: "Spatial Audio with Dynamic Head Tracking",
      Battery: "6 hrs (ANC) / 30 hrs (Case)",
      Charging: "USB-C, MagSafe, Qi, Apple Watch Charger",
      Controls: "Touch Control, Siri",
      WaterResistance: "IPX4 (Earbuds & Case)",
    },
    inStock: true,
    rating: 4.8,
    reviewCount: 3421,
    badge: "Best Seller",
  },
  {
    id: "sony-wh1000xm5",
    name: "Sony WH-1000XM5",
    description: "Industry-leading noise canceling. Exceptional sound quality. All-day comfort.",
    shortDescription: "Best ANC • 30hr Battery • Multipoint • Speak-to-Chat",
    price: 29990,
    originalPrice: 34990,
    category: "earbuds",
    brand: "sony",
    image: "/products/sony-wh1000xm5.svg",
    images: [
      "/products/sony-wh1000xm5-1.svg",
      "/products/sony-wh1000xm5-2.svg",
    ],
    features: [
      "Auto NC Optimizer",
      "Integrated Processor V1 + HD Noise Canceling Processor QN1",
      "30 Hours Battery (NC On)",
      "Multipoint Connection",
      "Speak-to-Chat & Quick Attention",
      "Lightweight Design (250g)",
    ],
    specifications: {
      Driver: "30mm Dynamic Driver",
      FrequencyResponse: "4Hz-40,000Hz (Wired)",
      NoiseCancellation: "Dual Noise Sensor Technology",
      Battery: "30 hrs (NC On) / 40 hrs (NC Off)",
      Charging: "USB-C, 3min = 3hrs Playback",
      Connectivity: "Bluetooth 5.2, LDAC, Multipoint",
      Weight: "250g",
      Accessories: "Carrying Case, Cable, Adapter",
    },
    inStock: true,
    rating: 4.7,
    reviewCount: 2156,
    badge: "Top Rated",
  },
  {
    id: "jbl-charge-5",
    name: "JBL Charge 5",
    description: "Bold JBL Original Pro Sound. Built-in Powerbank. 20 Hours Playtime. IP67 Waterproof.",
    shortDescription: "Pro Sound • Powerbank • 20hr Battery • IP67 • PartyBoost",
    price: 14999,
    originalPrice: 17999,
    category: "speakers",
    brand: "jbl",
    image: "/products/jbl-charge-5.svg",
    images: [
      "/products/jbl-charge-5-1.svg",
      "/products/jbl-charge-5-2.svg",
    ],
    features: [
      "JBL Original Pro Sound",
      "Built-in Powerbank (7500mAh)",
      "20 Hours Playtime",
      "IP67 Waterproof & Dustproof",
      "PartyBoost for Multi-Speaker",
      "Rugged Fabric & Rubber Housing",
    ],
    specifications: {
      OutputPower: "40W RMS",
      FrequencyResponse: "60Hz - 20kHz",
      Battery: "7500mAh Li-ion (20 hrs)",
      Charging: "USB-C, 4 Hours",
      Bluetooth: "5.1",
      Waterproof: "IP67",
      Dimensions: "223 x 96.5 x 94 mm",
      Weight: "960g",
    },
    inStock: true,
    rating: 4.6,
    reviewCount: 1834,
  },
  {
    id: "anker-737-powerbank",
    name: "Anker 737 Power Bank (PowerCore 24K)",
    description: "24,000mAh. 140W Total Output. Smart Digital Display. Charges MacBook Pro 16\" 1.3x.",
    shortDescription: "24,000mAh • 140W Output • Smart Display • PD 3.1",
    price: 13999,
    originalPrice: 15999,
    category: "power-banks",
    brand: "anker",
    image: "/products/anker-737-powerbank.svg",
    images: [
      "/products/anker-737-powerbank-1.svg",
    ],
    features: [
      "24,000mAh Capacity",
      "140W Total Output (PD 3.1)",
      "Smart Digital Display",
      "Charges MacBook Pro 16\" 1.3 Times",
      "3 Ports (2 USB-C, 1 USB-A)",
      "ActiveShield 2.0 Safety",
    ],
    specifications: {
      Capacity: "24,000mAh (86.4Wh)",
      USB_C1_Output: "140W Max (PD 3.1)",
      USB_C2_Output: "30W Max",
      USB_A_Output: "18W Max",
      TotalOutput: "140W Max",
      Input: "140W Max (USB-C1)",
      Display: "Smart Digital Display (W, V, A, %)",
      Weight: "630g",
      Dimensions: "155.8 x 55 x 49.5 mm",
    },
    inStock: true,
    rating: 4.7,
    reviewCount: 987,
    badge: "Best Value",
  },
  {
    id: "belkin-boostcharge-cable",
    name: "Belkin BOOST↑CHARGE Pro USB-C to USB-C Cable",
    description: "240W PD 3.1. E-Marker Chip. 2m Length. 30,000+ Bend Lifespan.",
    shortDescription: "240W PD 3.1 • 2m • E-Marker • 30k+ Bends • 5yr Warranty",
    price: 1499,
    originalPrice: 1999,
    category: "cables",
    brand: "belkin",
    image: "/products/belkin-cable.svg",
    images: [
      "/products/belkin-cable-1.svg",
    ],
    features: [
      "240W Power Delivery 3.1",
      "E-Marker Chip for Safe Charging",
      "30,000+ Bend Lifespan",
      "2 Meter Length",
      "5-Year Warranty",
      "Thunderbolt 4 Compatible",
    ],
    specifications: {
      PowerDelivery: "240W (PD 3.1)",
      DataTransfer: "480 Mbps (USB 2.0)",
      Length: "2m (6.6 ft)",
      Connector: "USB-C to USB-C",
      Certification: "USB-IF Certified",
      Warranty: "5 Years",
      Colors: "Black, White",
    },
    inStock: true,
    rating: 4.5,
    reviewCount: 567,
  },
]

export const offers = [
  {
    id: "weekly-deals",
    title: "Weekly Deals",
    description: "Fresh discounts every week on popular electronics. Limited stock available.",
    badge: "Ends Sunday",
    products: ["galaxy-s24-ultra", "airpods-pro-2", "jbl-charge-5", "belkin-boostcharge-cable"],
    background: "bg-gradient-to-br from-primary-50 to-primary-100 dark:from-primary-900/20 dark:to-primary-800/20",
    border: "border-primary-200 dark:border-primary-800",
  },
  {
    id: "festival-offers",
    title: "Festival Offers",
    description: "Celebrate with special prices on smartphones, laptops, and accessories. Extra exchange bonus available.",
    badge: "Diwali Special",
    products: ["iphone-15-pro-max", "macbook-air-m3", "galaxy-watch6-classic", "sony-wh1000xm5"],
    background: "bg-gradient-to-br from-accent-50 to-accent-100 dark:from-accent-900/20 dark:to-accent-800/20",
    border: "border-accent-200 dark:border-accent-800",
  },
  {
    id: "exchange-offers",
    title: "Exchange Offers",
    description: "Upgrade your device and get up to ₹15,000 extra exchange value on select models.",
    badge: "Limited Time",
    products: ["galaxy-s24-ultra", "iphone-15-pro-max", "dell-xps-14", "macbook-air-m3"],
    background: "bg-gradient-to-br from-whatsapp-50 to-whatsapp-100 dark:from-whatsapp-900/20 dark:to-whatsapp-800/20",
    border: "border-whatsapp-200 dark:border-whatsapp-800",
  },
  {
    id: "student-discounts",
    title: "Student Discounts",
    description: "Verified students get additional 5-10% off on laptops, tablets, and accessories.",
    badge: "Verify ID",
    products: ["macbook-air-m3", "dell-xps-14", "ipad-air-m2", "galaxy-tab-s9"],
    background: "bg-gradient-to-br from-green-50 to-green-100 dark:from-green-900/20 dark:to-green-800/20",
    border: "border-green-200 dark:border-green-800",
  },
]

export const services = [
  {
    id: "mobile-repair",
    name: "Mobile Repair",
    description: "Expert repair for all major brands. Screen replacement, battery, charging port, water damage, and more.",
    icon: "smartphone",
    features: ["Screen Replacement", "Battery Replacement", "Charging Port Repair", "Water Damage Recovery", "Software Issues", "Motherboard Repair"],
    price: "Starting ₹499",
    duration: "30-60 mins",
    warranty: "90 Days",
  },
  {
    id: "laptop-repair",
    name: "Laptop Repair",
    description: "Comprehensive laptop repair services. Hardware diagnostics, component replacement, data recovery.",
    icon: "laptop",
    features: ["Screen Replacement", "Keyboard Repair", "SSD/HDD Upgrade", "RAM Upgrade", "Cooling System Clean", "Motherboard Repair"],
    price: "Starting ₹799",
    duration: "1-3 hours",
    warranty: "90 Days",
  },
  {
    id: "software-installation",
    name: "Software Installation",
    description: "OS installation, driver updates, antivirus setup, productivity software, and system optimization.",
    icon: "monitor",
    features: ["Windows/macOS Install", "Driver Updates", "Antivirus Setup", "Office Suite Install", "System Optimization", "Data Backup & Restore"],
    price: "Starting ₹299",
    duration: "45-90 mins",
    warranty: "30 Days Support",
  },
  {
    id: "screen-replacement",
    name: "Screen Replacement",
    description: "Genuine quality screens for phones, tablets, and laptops. Professional installation with warranty.",
    icon: "monitor-smartphone",
    features: ["Genuine Parts", "OEM Quality Options", "Professional Installation", "Touch Calibration", "Oleophobic Coating", "Warranty Included"],
    price: "Starting ₹899",
    duration: "45-90 mins",
    warranty: "180 Days",
  },
  {
    id: "accessories",
    name: "Accessories",
    description: "Wide range of genuine and certified accessories. Cases, chargers, cables, screen protectors, and more.",
    icon: "package",
    features: ["Protective Cases", "Fast Chargers", "Data Cables", "Screen Protectors", "Wireless Chargers", "Car Mounts"],
    price: "From ₹199",
    duration: "Instant",
    warranty: "6-12 Months",
  },
  {
    id: "home-delivery",
    name: "Home Delivery",
    description: "Free delivery within city limits. Secure packaging. COD and online payment options available.",
    icon: "truck",
    features: ["Free City Delivery", "Secure Packaging", "COD Available", "Real-time Tracking", "Scheduled Delivery", "Easy Returns"],
    price: "Free > ₹1999",
    duration: "2-4 Hours",
    warranty: "7-Day Return",
  },
  {
    id: "warranty-support",
    name: "Warranty Support",
    description: "Authorized service partner for major brands. Hassle-free warranty claims and extended warranty options.",
    icon: "shield-check",
    features: ["Authorized Service", "Brand Warranty Claims", "Extended Warranty", "Doorstep Pickup", "Status Tracking", "Genuine Parts"],
    price: "As per Brand",
    duration: "5-7 Days",
    warranty: "Brand Warranty",
  },
]

export const testimonials = [
  {
    id: 1,
    name: "Rajesh Kumar",
    location: "Chikkamagaluru",
    rating: 5,
    text: "Excellent service! Got my iPhone screen replaced in under an hour with genuine parts. Staff was professional and explained everything clearly. Highly recommended!",
    avatar: "/avatars/rajesh.svg",
    verified: true,
  },
  {
    id: 2,
    name: "Priya Sharma",
    location: "Bangalore",
    rating: 5,
    text: "Bought a MacBook Air M3 from here. Best price in town with student discount. They helped with data transfer and setup. Great after-sales support too.",
    avatar: "/avatars/priya.svg",
    verified: true,
  },
  {
    id: 3,
    name: "Amit Patel",
    location: "Mangalore",
    rating: 4,
    text: "Good experience with laptop repair. My Dell XPS had heating issues, they cleaned the cooling system and replaced thermal paste. Working perfectly now.",
    avatar: "/avatars/amit.svg",
    verified: true,
  },
  {
    id: 4,
    name: "Sneha Reddy",
    location: "Mysore",
    rating: 5,
    text: "Ordered Samsung Galaxy S24 Ultra via WhatsApp. Got it delivered same day with all accessories. Price was better than online. Will definitely buy again!",
    avatar: "/avatars/sneha.svg",
    verified: true,
  },
]

export const faqs = [
  {
    id: 1,
    question: "Do you provide warranty on repairs?",
    answer: "Yes, all repairs come with a warranty period ranging from 30 to 180 days depending on the service. We use genuine or high-quality OEM parts.",
  },
  {
    id: 2,
    question: "Can I get a price quote before repair?",
    answer: "Absolutely! We provide free diagnostics and a detailed quote before any repair work begins. You approve the cost before we proceed.",
  },
  {
    id: 3,
    question: "Do you offer home pickup for repairs?",
    answer: "Yes, we offer free doorstep pickup and delivery for repairs within Chikkamagaluru city limits for orders above ₹1,999.",
  },
  {
    id: 4,
    question: "What payment methods do you accept?",
    answer: "We accept Cash, UPI (PhonePe, GPay, Paytm), Credit/Debit Cards, and Bank Transfers. COD available for product deliveries.",
  },
  {
    id: 5,
    question: "Are the products genuine with brand warranty?",
    answer: "Yes, we are authorized retailers for all major brands. All products come with official manufacturer warranty and valid GST invoice.",
  },
  {
    id: 6,
    question: "Do you have exchange offers on old devices?",
    answer: "Yes! We offer competitive exchange values for smartphones, laptops, and tablets. Get an instant quote via WhatsApp or visit our store.",
  },
  {
    id: 7,
    question: "What are your store timings?",
    answer: "We're open Monday to Saturday: 10:00 AM - 8:00 PM, Sunday: 11:00 AM - 6:00 PM. WhatsApp support available 24/7.",
  },
  {
    id: 8,
    question: "Can I track my repair status?",
    answer: "Yes, you'll receive real-time updates via WhatsApp/SMS at every stage: Received → Diagnostics → Quote → Repair → Quality Check → Ready for Pickup.",
  },
]

